export interface WorkflowStep {
  command: string;
  description: string;
  delay?: number;
}

export interface AgenticWorkflow {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: WorkflowCategory;
  model: string;
  tags: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedTime: string;
  steps: WorkflowStep[];
  useCases: string[];
  icon: string;
}

export type WorkflowCategory =
  | "Code Intelligence"
  | "Research & Analysis"
  | "Data Processing"
  | "Content Generation"
  | "Parallel Agents"
  | "DevOps & Deploy"
  | "AI & Models"
  | "Business & Strategy"
  | "Cloudflare Workers"
  | "Dynamic Workers";

export const WORKFLOW_CATEGORIES: WorkflowCategory[] = [
  "Code Intelligence",
  "Research & Analysis",
  "Data Processing",
  "Content Generation",
  "Parallel Agents",
  "DevOps & Deploy",
  "AI & Models",
  "Business & Strategy",
  "Cloudflare Workers",
  "Dynamic Workers",
];

export const AGENTIC_WORKFLOWS: AgenticWorkflow[] = [
  // ── Code Intelligence ──────────────────────────────────────────────────────
  {
    id: "code-reviewer",
    name: "Code Reviewer",
    tagline: "Deep AI-powered code analysis",
    description: "Runs a multi-pass review: security vulnerabilities, performance bottlenecks, style issues, and refactoring opportunities. Each pass runs in its own V8 isolate.",
    category: "Code Intelligence",
    model: "@cf/qwen/qwen2.5-coder-32b-instruct",
    tags: ["code", "security", "quality", "free"],
    difficulty: "beginner",
    estimatedTime: "~30s",
    icon: "🔍",
    useCases: ["Pull request reviews", "Security audits", "Code quality gates", "Onboarding new codebases"],
    steps: [
      { command: "remember context: Reviewing TypeScript Express API for code quality", description: "Load context into durable memory" },
      { command: "parallel 3 security vulnerability scan on auth middleware", description: "Spawn 3 isolates to scan in parallel" },
      { command: "analyze Check for N+1 query patterns in the database layer", description: "Performance analysis pass" },
      { command: "chat Summarize all issues found and prioritize by severity", description: "AI synthesis of findings" },
    ],
  },
  {
    id: "bug-hunter",
    name: "Bug Hunter",
    tagline: "Find and fix bugs automatically",
    description: "Systematically hunts for bugs by analyzing stack traces, reproducing conditions in isolated environments, generating fix candidates, and validating them.",
    category: "Code Intelligence",
    model: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    tags: ["debugging", "code", "reasoning", "free"],
    difficulty: "intermediate",
    estimatedTime: "~45s",
    icon: "🐛",
    useCases: ["Production incident response", "Flaky test diagnosis", "Memory leak detection", "Race condition hunting"],
    steps: [
      { command: "remember error: TypeError: Cannot read property 'id' of undefined at line 42", description: "Load error context" },
      { command: "analyze Trace all code paths that could produce a null/undefined object at line 42", description: "Root cause analysis" },
      { command: "parallel 3 generate fix candidates for the null reference bug", description: "Generate multiple fix options in parallel" },
      { command: "chat Rank the fix candidates by correctness and minimal diff, output the best one", description: "AI selects the best fix" },
    ],
  },
  {
    id: "test-generator",
    name: "Test Generator",
    tagline: "Auto-generate test suites from code",
    description: "Analyzes your source code, generates unit tests for all functions, integration tests for all routes, and edge case tests for complex logic.",
    category: "Code Intelligence",
    model: "@cf/qwen/qwq-32b",
    tags: ["testing", "tdd", "quality", "code", "free"],
    difficulty: "intermediate",
    estimatedTime: "~40s",
    icon: "🧪",
    useCases: ["Test coverage improvement", "TDD bootstrap", "Regression test generation", "API contract testing"],
    steps: [
      { command: "remember source: Express session management API with 8 routes", description: "Load source code context" },
      { command: "parallel 4 generate tests for: CRUD routes, auth middleware, error handling, edge cases", description: "4 parallel test generation workers" },
      { command: "analyze Review generated tests for completeness and identify gaps", description: "Coverage analysis" },
      { command: "chat Output final test file with Jest configuration and coverage report", description: "Final test suite assembly" },
    ],
  },
  {
    id: "security-auditor",
    name: "Security Auditor",
    tagline: "OWASP-aligned vulnerability scanning",
    description: "Scans your codebase for OWASP Top 10 vulnerabilities, checks dependency CVEs, identifies auth weaknesses, and generates a security report with severity ratings.",
    category: "Code Intelligence",
    model: "@cf/deepseek-ai/deepseek-r1-distill-llama-70b",
    tags: ["security", "owasp", "audit", "compliance"],
    difficulty: "advanced",
    estimatedTime: "~50s",
    icon: "🛡️",
    useCases: ["Pre-deployment security checks", "SOC2 compliance prep", "Penetration test support", "Dependency auditing"],
    steps: [
      { command: "remember target: Node.js Express app with JWT auth and PostgreSQL", description: "Load audit target context" },
      { command: "parallel 5 scan for OWASP Top 10 category vulnerabilities", description: "5 parallel security scanners" },
      { command: "analyze Correlate findings and identify attack chains between vulnerabilities", description: "Attack chain analysis" },
      { command: "chat Generate CVSS-scored security report with remediation priorities", description: "Final security report" },
    ],
  },
  {
    id: "refactor-agent",
    name: "Refactor Agent",
    tagline: "Automated code modernization",
    description: "Analyzes legacy code patterns, proposes modern equivalents, refactors functions to be more readable, extracts reusable utilities, and documents all changes.",
    category: "Code Intelligence",
    model: "@cf/qwen/qwen2.5-coder-32b-instruct",
    tags: ["refactor", "code", "modernize", "free"],
    difficulty: "intermediate",
    estimatedTime: "~35s",
    icon: "♻️",
    useCases: ["Legacy code migration", "TypeScript conversion", "Design pattern adoption", "Tech debt reduction"],
    steps: [
      { command: "remember codebase: Express 4 callback-based API with 2000 lines of mixed concerns", description: "Load codebase context" },
      { command: "parallel 3 identify: callback hells, god functions, magic numbers, duplicated logic", description: "3 parallel smell detectors" },
      { command: "analyze Propose refactoring plan with before/after code for top 5 issues", description: "Refactoring plan generation" },
      { command: "chat Output the refactored version of the highest-impact function", description: "Generate refactored code" },
    ],
  },
  {
    id: "pr-reviewer",
    name: "PR Review Agent",
    tagline: "AI-powered pull request analysis",
    description: "Reviews a GitHub PR diff end-to-end: checks for breaking changes, validates test coverage, assesses performance impact, and posts structured review comments.",
    category: "Code Intelligence",
    model: "deepseek-chat",
    tags: ["git", "pr", "review", "code"],
    difficulty: "beginner",
    estimatedTime: "~25s",
    icon: "🔀",
    useCases: ["GitHub PR automation", "Code ownership enforcement", "Release gate checks", "Junior dev mentoring"],
    steps: [
      { command: "remember diff: 150-line change adding Redis caching to session middleware", description: "Load PR diff" },
      { command: "parallel 3 review for: correctness, security, and performance impact", description: "3 parallel review passes" },
      { command: "analyze Check if new code has adequate test coverage and error handling", description: "Test coverage check" },
      { command: "chat Output structured PR review with inline comments and overall verdict", description: "Generate review output" },
    ],
  },

  // ── Research & Analysis ────────────────────────────────────────────────────
  {
    id: "research-agent",
    name: "Research Assistant",
    tagline: "Multi-source research with citations",
    description: "Breaks down a research question into sub-tasks, dispatches parallel research agents, synthesizes findings, and produces a structured report with citations.",
    category: "Research & Analysis",
    model: "@cf/moonshotai/kimi-k2.5",
    tags: ["research", "synthesis", "citations", "parallel"],
    difficulty: "intermediate",
    estimatedTime: "~60s",
    icon: "📚",
    useCases: ["Market research", "Competitive analysis", "Technical due diligence", "Literature reviews"],
    steps: [
      { command: "remember topic: Cloudflare Workers vs AWS Lambda edge performance", description: "Store research topic" },
      { command: "parallel 5 research sub-question about cold start latency benchmarks", description: "5 parallel research agents" },
      { command: "analyze Consolidate all research findings into structured insights", description: "Synthesis pass" },
      { command: "chat Format as executive summary with key findings and citations", description: "Generate final report" },
    ],
  },
  {
    id: "competitive-intel",
    name: "Competitive Intel Agent",
    tagline: "Automated competitive analysis",
    description: "Takes a list of competitors, spawns parallel research agents for each, extracts pricing, features, weaknesses, and synthesizes a battle card and SWOT.",
    category: "Research & Analysis",
    model: "@cf/moonshotai/kimi-k2.5",
    tags: ["research", "competitive", "strategy", "parallel"],
    difficulty: "advanced",
    estimatedTime: "~70s",
    icon: "📡",
    useCases: ["Sales battle cards", "Product positioning", "Pricing strategy", "Feature gap analysis"],
    steps: [
      { command: "remember competitors: Vercel AI SDK, LangChain, Modal Labs, Replicate", description: "Load competitor list" },
      { command: "parallel 4 research each competitor: pricing, features, weaknesses, positioning", description: "4 agents in parallel" },
      { command: "analyze Build comparison matrix across all competitors vs OpenClaw", description: "Competitive matrix" },
      { command: "chat Generate battle card and SWOT analysis for sales team", description: "Battle card generation" },
    ],
  },
  {
    id: "trend-spotter",
    name: "Trend Spotter",
    tagline: "Identify emerging trends before they peak",
    description: "Analyzes signals across tech, markets, and social domains to identify emerging trends, scores them by trajectory, and ranks by potential impact on your industry.",
    category: "Research & Analysis",
    model: "sonar-pro",
    tags: ["research", "trends", "strategy", "search"],
    difficulty: "intermediate",
    estimatedTime: "~50s",
    icon: "📈",
    useCases: ["Product roadmap decisions", "Investment thesis validation", "Content strategy", "Technology scouting"],
    steps: [
      { command: "remember domain: AI infrastructure and developer tools Q2 2026", description: "Load research domain" },
      { command: "parallel 4 identify trends in: open-source models, inference hardware, deployment patterns, pricing", description: "4 parallel trend searches" },
      { command: "analyze Score each trend by: velocity, relevance, and competitive impact", description: "Trend scoring" },
      { command: "chat Output ranked trend report with 3-month and 12-month projections", description: "Trend forecast report" },
    ],
  },
  {
    id: "literature-reviewer",
    name: "Literature Reviewer",
    tagline: "Academic paper synthesis at scale",
    description: "Reads and synthesizes academic papers or technical blogs on a topic, extracts key findings, identifies consensus vs controversy, and outputs an annotated bibliography.",
    category: "Research & Analysis",
    model: "gemini-2.0-flash",
    tags: ["research", "academic", "synthesis", "knowledge"],
    difficulty: "intermediate",
    estimatedTime: "~60s",
    icon: "📖",
    useCases: ["Academic research", "Technology assessment", "Patent landscape analysis", "Due diligence"],
    steps: [
      { command: "remember topic: Flash attention and efficient transformer training techniques", description: "Load research topic" },
      { command: "parallel 5 summarize key papers: FlashAttention, FlashAttention-2, Ring Attention, GQA, MQA", description: "5 parallel paper summaries" },
      { command: "analyze Identify consensus findings, open questions, and implementation gaps", description: "Cross-paper synthesis" },
      { command: "chat Output annotated bibliography with impact scores and recommended reading order", description: "Generate bibliography" },
    ],
  },

  // ── Data Processing ────────────────────────────────────────────────────────
  {
    id: "data-pipeline",
    name: "Data Pipeline Agent",
    tagline: "Transform and analyze data at scale",
    description: "Ingests raw data (CSV, JSON, logs), validates schema, runs statistical analysis across parallel workers, detects anomalies, and outputs a clean transformed dataset.",
    category: "Data Processing",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["data", "pipeline", "parallel", "free"],
    difficulty: "beginner",
    estimatedTime: "~40s",
    icon: "📊",
    useCases: ["ETL pipelines", "Log analysis", "Data quality checks", "Anomaly detection"],
    steps: [
      { command: "remember schema: {userId: string, amount: number, timestamp: ISO8601, status: enum}", description: "Load data schema" },
      { command: "parallel 4 validate and clean records batch", description: "Parallel validation" },
      { command: "analyze Run statistical summary: mean, std, outliers, missing values", description: "Statistical analysis" },
      { command: "chat Generate data quality report and flag rows requiring manual review", description: "Data quality report" },
    ],
  },
  {
    id: "log-analyzer",
    name: "Log Intelligence",
    tagline: "Turn logs into actionable insights",
    description: "Ingests application logs, identifies error patterns, correlates events across services, detects anomalies, and generates an incident timeline with root cause hypotheses.",
    category: "Data Processing",
    model: "@cf/google/gemma-3-27b-it",
    tags: ["logs", "observability", "monitoring", "free"],
    difficulty: "intermediate",
    estimatedTime: "~30s",
    icon: "🔬",
    useCases: ["Incident post-mortems", "SLA violation analysis", "Error rate investigation", "Performance regression hunting"],
    steps: [
      { command: "remember logs: 500 nginx error logs from 2026-03-25T07:00-08:00 UTC", description: "Load log window" },
      { command: "parallel 3 analyze logs by: error type, affected endpoint, client IP pattern", description: "3 parallel analysis angles" },
      { command: "analyze Build incident timeline correlating all anomalies found", description: "Timeline correlation" },
      { command: "chat Generate incident report with root cause hypotheses and confidence scores", description: "Incident report" },
    ],
  },
  {
    id: "csv-analyst",
    name: "CSV Data Analyst",
    tagline: "Instant insights from any CSV",
    description: "Takes a CSV description, identifies columns, infers data types, generates statistical profiles, finds correlations, and produces business insights with chart recommendations.",
    category: "Data Processing",
    model: "deepseek-chat",
    tags: ["data", "csv", "analysis", "insights"],
    difficulty: "beginner",
    estimatedTime: "~30s",
    icon: "📋",
    useCases: ["Sales data analysis", "Customer segmentation", "Financial reporting", "Survey analysis"],
    steps: [
      { command: "remember csv: columns=[date,revenue,region,product,quantity,discount] 10K rows Q1 2026", description: "Load CSV schema" },
      { command: "parallel 3 analyze: revenue trends by region, top products, discount impact on margin", description: "3 parallel analysis threads" },
      { command: "analyze Identify the top 3 business insights and actionable recommendations", description: "Insight extraction" },
      { command: "chat Output executive summary with charts description and SQL queries for each finding", description: "Generate final report" },
    ],
  },
  {
    id: "sql-optimizer",
    name: "SQL Query Optimizer",
    tagline: "Make your slow queries 10x faster",
    description: "Analyzes slow SQL queries, explains query plans, identifies missing indexes, rewrites inefficient joins, and benchmarks before/after performance.",
    category: "Data Processing",
    model: "@cf/defog/sqlcoder-7b-2",
    tags: ["sql", "database", "performance", "free"],
    difficulty: "intermediate",
    estimatedTime: "~25s",
    icon: "⚡",
    useCases: ["Database performance tuning", "Query plan optimization", "Index design", "N+1 elimination"],
    steps: [
      { command: "remember query: SELECT u.*, COUNT(o.id) FROM users u LEFT JOIN orders o ON... (12 joins, 2s latency)", description: "Load slow query" },
      { command: "analyze Explain the query execution plan and identify the most expensive operations", description: "Query plan analysis" },
      { command: "parallel 3 generate optimized versions: indexed, rewritten joins, materialized CTE", description: "3 optimization strategies" },
      { command: "chat Compare all versions, explain tradeoffs, and output the recommended query with index DDL", description: "Final recommendation" },
    ],
  },

  // ── Content Generation ─────────────────────────────────────────────────────
  {
    id: "content-factory",
    name: "Content Factory",
    tagline: "Scale content production with agents",
    description: "Takes a content brief and spawns specialized agents for research, outlining, drafting, SEO optimization, and editing — all running in parallel.",
    category: "Content Generation",
    model: "@cf/mistral/mistral-small-3.1-24b-instruct",
    tags: ["content", "seo", "writing", "parallel", "free"],
    difficulty: "beginner",
    estimatedTime: "~55s",
    icon: "✍️",
    useCases: ["Blog post generation", "Product descriptions", "Email campaigns", "Social media content"],
    steps: [
      { command: "remember brief: 1500-word technical blog post about Cloudflare Durable Objects", description: "Store content brief" },
      { command: "parallel 3 research key topics: architecture, use cases, performance benchmarks", description: "3 parallel research agents" },
      { command: "analyze Create detailed outline with SEO-optimized H2/H3 structure", description: "Outline + SEO" },
      { command: "chat Draft the full article following the outline, matching target word count", description: "Full article generation" },
    ],
  },
  {
    id: "api-doc-generator",
    name: "API Documenter",
    tagline: "Auto-generate beautiful API docs",
    description: "Reads your OpenAPI spec or Express routes, generates comprehensive documentation with examples, describes edge cases, and outputs ready-to-publish MDX docs.",
    category: "Content Generation",
    model: "@cf/qwen/qwen2.5-coder-32b-instruct",
    tags: ["docs", "api", "openapi", "code", "free"],
    difficulty: "beginner",
    estimatedTime: "~35s",
    icon: "📝",
    useCases: ["Developer portals", "Internal API wikis", "SDK documentation", "Changelog generation"],
    steps: [
      { command: "remember spec: POST /sessions {name, model} → {id, status, createdAt}", description: "Load API spec" },
      { command: "analyze Generate documentation for all endpoints including error responses", description: "Doc generation pass" },
      { command: "parallel 3 generate code examples in Python, JavaScript, and cURL", description: "SDK examples in parallel" },
      { command: "chat Format as MDX with frontmatter, code blocks, and parameter tables", description: "Final MDX output" },
    ],
  },
  {
    id: "email-drip",
    name: "Email Drip Campaign",
    tagline: "Full email sequence in minutes",
    description: "Designs a 5-email onboarding or sales drip sequence, writes each email with subject lines, personalisation tokens, CTAs, and A/B test variants.",
    category: "Content Generation",
    model: "gpt-5-mini",
    tags: ["email", "marketing", "content", "saas"],
    difficulty: "beginner",
    estimatedTime: "~40s",
    icon: "📧",
    useCases: ["SaaS onboarding sequences", "Sales nurturing", "Re-engagement campaigns", "Product launch announcements"],
    steps: [
      { command: "remember product: AI Agent Sandbox — turns natural language into spawned AI agents", description: "Load product context" },
      { command: "parallel 5 write emails: welcome, first value, feature discovery, upgrade nudge, win-back", description: "5 emails in parallel" },
      { command: "analyze Review for tone consistency, clear CTAs, and persuasion best practices", description: "Quality review pass" },
      { command: "chat Output final sequence with subject lines, preview text, and A/B variant for each", description: "Final sequence assembly" },
    ],
  },
  {
    id: "social-media-agent",
    name: "Social Media Agent",
    tagline: "Viral content for every platform",
    description: "Takes a topic or product and generates platform-optimized content for Twitter/X, LinkedIn, and Reddit — each tuned to that platform's culture and format.",
    category: "Content Generation",
    model: "gpt-5-mini",
    tags: ["social", "twitter", "linkedin", "content", "marketing"],
    difficulty: "beginner",
    estimatedTime: "~25s",
    icon: "🌐",
    useCases: ["Product launches", "Developer announcements", "Thought leadership", "Community building"],
    steps: [
      { command: "remember announcement: OpenClaw now has 23 AI providers and 200+ models", description: "Load announcement context" },
      { command: "parallel 3 draft posts for: Twitter/X thread, LinkedIn article, Reddit HackerNews submission", description: "3 platform-specific posts" },
      { command: "analyze Review for each platform's best practices, tone, and viral potential", description: "Platform optimization review" },
      { command: "chat Output final posts with character counts, hashtag strategy, and best posting time", description: "Final content output" },
    ],
  },

  // ── Parallel Agents ────────────────────────────────────────────────────────
  {
    id: "parallel-comparator",
    name: "Multi-Model Comparator",
    tagline: "Same prompt, 5 models simultaneously",
    description: "Runs your prompt through 5 different Workers AI models in parallel V8 isolates, then compares outputs by accuracy, reasoning depth, and response style.",
    category: "Parallel Agents",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["parallel", "models", "comparison", "benchmarking"],
    difficulty: "advanced",
    estimatedTime: "~20s",
    icon: "⚡",
    useCases: ["Model selection for production", "Prompt quality testing", "Cost vs quality tradeoffs", "Regression testing"],
    steps: [
      { command: "remember prompt: Explain quantum entanglement in simple terms", description: "Store prompt" },
      { command: "parallel 5 run stored prompt across frontier models", description: "5 models simultaneously" },
      { command: "analyze Score each model response on clarity, accuracy, and conciseness", description: "Evaluation pass" },
      { command: "chat Rank models and recommend best for this type of explanation task", description: "Final recommendation" },
    ],
  },
  {
    id: "debate-arena",
    name: "AI Debate Arena",
    tagline: "Multi-agent perspective battle",
    description: "Spawns agents to argue both sides of a question simultaneously, then a judge agent evaluates argument quality, logical coherence, and evidence strength.",
    category: "Parallel Agents",
    model: "@cf/nvidia/nemotron-3-120b-a12b",
    tags: ["parallel", "debate", "reasoning", "multi-agent"],
    difficulty: "advanced",
    estimatedTime: "~45s",
    icon: "⚔️",
    useCases: ["Decision analysis", "Policy evaluation", "Technical tradeoff assessment", "Risk analysis"],
    steps: [
      { command: "remember question: Should we migrate from PostgreSQL to CockroachDB for global distribution?", description: "Load debate question" },
      { command: "parallel 2 argue both sides: FOR migration and AGAINST migration with evidence", description: "2 debate agents argue simultaneously" },
      { command: "analyze Judge the debate: evaluate logical strength, evidence quality, real-world applicability", description: "AI judge evaluation" },
      { command: "chat Output structured decision framework with risks, benefits, and recommended path", description: "Final decision framework" },
    ],
  },
  {
    id: "swarm-researcher",
    name: "Swarm Research Agent",
    tagline: "20 agents, 1 comprehensive answer",
    description: "Spawns a swarm of 20 specialized mini-agents each researching a different facet of your question, then aggregates all findings into one definitive response.",
    category: "Parallel Agents",
    model: "llama-3.1-8b-instant",
    tags: ["parallel", "swarm", "research", "scale"],
    difficulty: "advanced",
    estimatedTime: "~90s",
    icon: "🐝",
    useCases: ["Complex research questions", "Technology evaluation", "Market landscape mapping", "Strategy development"],
    steps: [
      { command: "remember question: What are all the ways to reduce LLM inference costs in 2026?", description: "Load research question" },
      { command: "parallel 10 research: quantization, speculative decoding, caching, batching, routing, fine-tuning, distillation, hardware, pricing, open-source", description: "10-agent swarm launches" },
      { command: "analyze Aggregate all findings and rank by cost-reduction potential and implementation difficulty", description: "Swarm aggregation" },
      { command: "chat Output comprehensive ranked guide with effort vs impact matrix", description: "Final synthesis" },
    ],
  },

  // ── DevOps & Deploy ────────────────────────────────────────────────────────
  {
    id: "deploy-validator",
    name: "Deploy Validator",
    tagline: "Pre-flight checks before every deploy",
    description: "Runs a comprehensive pre-deploy checklist: env var validation, dependency audit, smoke tests against staging, bundle size analysis, and rollback plan generation.",
    category: "DevOps & Deploy",
    model: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    tags: ["devops", "ci", "deploy", "validation", "free"],
    difficulty: "intermediate",
    estimatedTime: "~25s",
    icon: "🚀",
    useCases: ["CI/CD gate checks", "Zero-downtime deployments", "Staging validation", "Rollback planning"],
    steps: [
      { command: "remember target: wrangler deploy cloudflare-worker/ to production", description: "Load deploy target" },
      { command: "parallel 4 run pre-deploy checks: env vars, types, bundle size, migrations", description: "4 parallel pre-flight checks" },
      { command: "analyze Assess risk level of this deployment based on change diff", description: "Risk assessment" },
      { command: "chat Generate deploy runbook with rollback commands if checks pass", description: "Go/no-go decision + runbook" },
    ],
  },
  {
    id: "incident-responder",
    name: "Incident Responder",
    tagline: "Automated on-call intelligence",
    description: "Analyzes production alerts, correlates with recent deploys, queries error logs, identifies root cause, drafts comms, and generates a remediation runbook.",
    category: "DevOps & Deploy",
    model: "deepseek-reasoner",
    tags: ["devops", "ops", "incident", "monitoring"],
    difficulty: "advanced",
    estimatedTime: "~35s",
    icon: "🚨",
    useCases: ["Production outage response", "Alert triage", "Post-mortem generation", "On-call automation"],
    steps: [
      { command: "remember alert: P0 — API error rate 45% spike since 14:32 UTC, last deploy 14:15", description: "Load incident context" },
      { command: "parallel 3 investigate: recent deploy diff, error log patterns, database query latency", description: "3 parallel investigation threads" },
      { command: "analyze Correlate all findings and identify root cause with confidence score", description: "Root cause analysis" },
      { command: "chat Generate incident timeline, customer comms draft, and rollback runbook", description: "Incident response package" },
    ],
  },
  {
    id: "infrastructure-auditor",
    name: "Infrastructure Auditor",
    tagline: "Cloud cost and security audit",
    description: "Reviews your infrastructure configuration for cost optimization opportunities, security misconfigurations, unused resources, and compliance violations.",
    category: "DevOps & Deploy",
    model: "gpt-4o",
    tags: ["devops", "cloud", "cost", "security", "compliance"],
    difficulty: "advanced",
    estimatedTime: "~50s",
    icon: "🏗️",
    useCases: ["Cloud cost reduction", "Security hardening", "Compliance audit", "FinOps review"],
    steps: [
      { command: "remember config: 3 Cloudflare Workers, 2 D1 databases, 1 R2 bucket, Stripe billing", description: "Load infrastructure config" },
      { command: "parallel 4 audit: security posture, cost optimization, compliance, performance", description: "4 parallel audit dimensions" },
      { command: "analyze Prioritize findings by business impact and implementation effort", description: "Priority matrix" },
      { command: "chat Output audit report with specific remediation steps and estimated savings", description: "Final audit report" },
    ],
  },

  // ── AI & Models ────────────────────────────────────────────────────────────
  {
    id: "prompt-optimizer",
    name: "Prompt Optimizer",
    tagline: "Engineer perfect prompts automatically",
    description: "Tests your prompt across multiple models and strategies (few-shot, chain-of-thought, role-play), measures output quality, and returns the highest-performing variant.",
    category: "AI & Models",
    model: "@cf/nvidia/nemotron-3-120b-a12b",
    tags: ["prompts", "optimization", "ai", "quality"],
    difficulty: "intermediate",
    estimatedTime: "~40s",
    icon: "🎯",
    useCases: ["Production prompt engineering", "A/B testing prompts", "Cost reduction via better prompts", "Quality improvement"],
    steps: [
      { command: "remember prompt: Classify customer support tickets by urgency and department", description: "Load base prompt" },
      { command: "parallel 5 test prompt variants: zero-shot, few-shot, chain-of-thought, role-play, structured output", description: "5 variant evaluations" },
      { command: "analyze Score each variant on accuracy, consistency, token efficiency, and edge case handling", description: "Quality scoring" },
      { command: "chat Output the best prompt with explanation and usage instructions", description: "Final optimized prompt" },
    ],
  },
  {
    id: "model-benchmarker",
    name: "Model Benchmarker",
    tagline: "Find the best model for your task",
    description: "Runs a structured benchmark across all configured providers — testing speed, quality, cost per token, and consistency — then scores and ranks each model.",
    category: "AI & Models",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["benchmark", "models", "evaluation", "free"],
    difficulty: "advanced",
    estimatedTime: "~120s",
    icon: "🏎️",
    useCases: ["Model selection", "Cost optimization", "Quality baselines", "Provider comparison"],
    steps: [
      { command: "remember benchmark: code generation task — write a binary search tree in TypeScript", description: "Load benchmark task" },
      { command: "parallel 8 run benchmark against: GPT-4o, Claude 3.5, Groq Llama 70B, DeepSeek V3, Gemini Flash, Mistral Large, Qwen 72B, Cerebras", description: "8 models benchmarked simultaneously" },
      { command: "analyze Score each model on: correctness, latency, cost, code style, error handling", description: "Multi-dimensional scoring" },
      { command: "chat Output leaderboard with recommendations for different budget/quality tiers", description: "Benchmark leaderboard" },
    ],
  },
  {
    id: "rag-builder",
    name: "RAG Pipeline Builder",
    tagline: "Build retrieval-augmented generation systems",
    description: "Designs and validates a RAG architecture for your documents: chunking strategy, embedding choice, vector store config, query pipeline, and evaluation harness.",
    category: "AI & Models",
    model: "command-r-plus",
    tags: ["rag", "embeddings", "knowledge", "ai"],
    difficulty: "advanced",
    estimatedTime: "~50s",
    icon: "🧠",
    useCases: ["Enterprise knowledge base", "Customer support AI", "Document Q&A", "Code search"],
    steps: [
      { command: "remember corpus: 500 technical support tickets + product documentation, 2M tokens total", description: "Load corpus context" },
      { command: "parallel 3 design: chunking strategy, embedding model selection, retrieval algorithm", description: "3 parallel design passes" },
      { command: "analyze Evaluate retrieval quality with precision@k and RAGAS metrics", description: "Quality evaluation" },
      { command: "chat Output complete RAG implementation plan with code snippets and architecture diagram", description: "Final RAG blueprint" },
    ],
  },

  // ── Business & Strategy ────────────────────────────────────────────────────
  {
    id: "pricing-strategist",
    name: "Pricing Strategist",
    tagline: "Optimize your SaaS pricing",
    description: "Analyzes your product, market positioning, and competitors to design an optimal pricing structure with tier definitions, feature allocation, and revenue projections.",
    category: "Business & Strategy",
    model: "gpt-5.2",
    tags: ["business", "pricing", "strategy", "saas"],
    difficulty: "advanced",
    estimatedTime: "~45s",
    icon: "💰",
    useCases: ["SaaS pricing design", "Plan restructuring", "Enterprise tier creation", "Freemium strategy"],
    steps: [
      { command: "remember product: AI Agent Platform with token-based billing, 23 providers, 200+ models", description: "Load product context" },
      { command: "parallel 3 research: competitor pricing, customer segments, value metrics", description: "3 parallel pricing research agents" },
      { command: "analyze Design 3-tier pricing structure with feature allocation and psychological anchoring", description: "Pricing design pass" },
      { command: "chat Output pricing page copy, tier comparison table, and 12-month revenue projection model", description: "Final pricing strategy" },
    ],
  },
  {
    id: "user-journey-mapper",
    name: "User Journey Mapper",
    tagline: "Visualize and optimize user paths",
    description: "Maps the complete user journey from awareness to activation, identifies friction points, proposes improvements, and generates a product roadmap prioritized by impact.",
    category: "Business & Strategy",
    model: "claude-3-7-sonnet-20250219",
    tags: ["product", "ux", "strategy", "journey"],
    difficulty: "intermediate",
    estimatedTime: "~40s",
    icon: "🗺️",
    useCases: ["Onboarding optimization", "Conversion rate improvement", "Churn reduction", "Feature prioritization"],
    steps: [
      { command: "remember product: AI sandbox where developers spawn agents from terminal commands", description: "Load product context" },
      { command: "parallel 4 analyze journeys: first visit, first agent creation, first parallel run, upgrade moment", description: "4 journey analyses" },
      { command: "analyze Identify top 5 drop-off points and friction moments across all journeys", description: "Friction analysis" },
      { command: "chat Output journey maps with specific fixes, copy suggestions, and A/B test ideas", description: "Journey map output" },
    ],
  },

  // ── Cloudflare Workers Templates ──────────────────────────────────────────
  {
    id: "cf-llm-chat",
    name: "LLM Chat App",
    tagline: "Workers AI chat — deploy in 60 seconds",
    description: "Scaffold and deploy a complete LLM chat application powered by Cloudflare Workers AI with streaming responses, message history, and a clean UI. One wrangler deploy away from production.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["workers-ai", "chat", "llm", "free", "cloudflare"],
    difficulty: "beginner",
    estimatedTime: "~2 min",
    icon: "💬",
    useCases: ["Customer support chatbot", "AI assistant", "Knowledge base Q&A", "Developer playground"],
    steps: [
      { command: "remember template: LLM Chat App — Cloudflare Workers AI + streaming + message history", description: "Load template context" },
      { command: "chat Scaffold a complete Cloudflare Workers AI chat app: worker.ts with streaming, wrangler.jsonc config, and index.html UI", description: "Generate complete template code" },
      { command: "analyze Review the code for security, error handling, and Workers AI best practices", description: "Quality review" },
      { command: "chat Generate wrangler deploy commands and environment variable setup instructions", description: "Deploy instructions" },
    ],
  },
  {
    id: "cf-durable-chat",
    name: "Durable Chat App",
    tagline: "Real-time multi-user chat with Durable Objects",
    description: "Build a real-time chat room where multiple users connect via WebSocket, powered by Cloudflare Durable Objects for state persistence and PartyKit for multiplayer sync.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["durable-objects", "websocket", "real-time", "free", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~3 min",
    icon: "🔄",
    useCases: ["Live collaboration", "Multiplayer games", "Real-time notifications", "Event broadcasting"],
    steps: [
      { command: "remember template: Durable Chat — Durable Objects, WebSocket hibernation, PartyKit", description: "Load DO context" },
      { command: "chat Write the complete Durable Object class with WebSocket hibernation API: handleConnect, broadcast, onMessage", description: "Generate Durable Object code" },
      { command: "parallel 2 generate: Worker entry point for routing + frontend HTML with WebSocket client", description: "Parallel code generation" },
      { command: "chat Provide wrangler.jsonc with DO bindings, migration config, and deployment steps", description: "Config and deploy" },
    ],
  },
  {
    id: "cf-d1-database",
    name: "Worker + D1 Database",
    tagline: "Serverless SQL at the edge",
    description: "Create a Cloudflare Worker with D1 SQLite database binding — full CRUD API with Drizzle ORM or raw SQL, migrations, and type-safe queries. Deploy globally in seconds.",
    category: "Cloudflare Workers",
    model: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    tags: ["d1", "sqlite", "database", "rest-api", "free", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~3 min",
    icon: "🗄️",
    useCases: ["REST API backend", "User data storage", "Analytics aggregation", "Inventory management"],
    steps: [
      { command: "remember template: Worker + D1 — full CRUD API, Drizzle ORM, type-safe queries", description: "Load D1 template" },
      { command: "chat Design the D1 schema and Drizzle ORM models for a complete REST API backend", description: "Schema design" },
      { command: "chat Write the complete Worker with GET, POST, PUT, DELETE handlers using D1 bindings", description: "API implementation" },
      { command: "chat Generate migration SQL, wrangler.jsonc with D1 binding, and npx wrangler d1 commands", description: "Migration + deploy guide" },
    ],
  },
  {
    id: "cf-workflows-starter",
    name: "Cloudflare Workflows",
    tagline: "Durable multi-step workflows at the edge",
    description: "Build long-running, fault-tolerant workflows with Cloudflare Workflows API — automatic retries, sleep/wake, real-time status updates, and human-in-the-loop steps.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["workflows", "durable", "async", "orchestration", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~3 min",
    icon: "⚙️",
    useCases: ["Payment processing", "Email sequences", "Data ETL pipelines", "Approval workflows"],
    steps: [
      { command: "remember template: Cloudflare Workflows — WorkflowEntrypoint, steps, sleep, retries", description: "Load Workflows context" },
      { command: "chat Scaffold a complete Cloudflare Workflow class with 3+ steps, retry config, and sleep between steps", description: "Workflow class generation" },
      { command: "chat Write the Worker trigger endpoint and status polling API with WorkflowEvent type", description: "Trigger + status API" },
      { command: "chat Generate wrangler.jsonc with workflows binding and end-to-end test commands", description: "Config and test guide" },
    ],
  },
  {
    id: "cf-openauth",
    name: "OpenAuth Server",
    tagline: "OAuth 2.0 / OIDC server on Cloudflare Workers",
    description: "Deploy a complete OpenAuth server on Cloudflare Workers — OAuth 2.0 + OIDC provider with D1 user storage, PKCE, JWT tokens, and multiple grant types.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["auth", "oauth", "oidc", "jwt", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "🔐",
    useCases: ["SSO provider", "API authorization", "Multi-tenant auth", "Internal tool login"],
    steps: [
      { command: "remember template: OpenAuth — OAuth 2.0, OIDC, PKCE, D1 storage, JWT, @openauthjs/openauth", description: "Load auth context" },
      { command: "chat Scaffold the OpenAuth server: authorization endpoint, token endpoint, JWKS, userinfo", description: "Auth server scaffolding" },
      { command: "parallel 2 generate: D1 schema for users+sessions + Worker routing with @openauthjs/openauth", description: "Schema + routing" },
      { command: "chat Write client registration, PKCE flow, and refresh token rotation code", description: "PKCE implementation" },
    ],
  },
  {
    id: "cf-r2-explorer",
    name: "R2 Storage Explorer",
    tagline: "Google Drive UI for your R2 buckets",
    description: "Build a full file manager web UI for Cloudflare R2 — browse buckets, upload/download files, preview images, manage folders, and control public access. Like Google Drive for R2.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["r2", "storage", "files", "ui", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~4 min",
    icon: "📁",
    useCases: ["Media library", "Document storage", "Static asset CDN", "Build artifact storage"],
    steps: [
      { command: "remember template: R2 Explorer — R2 binding, multipart upload, signed URLs, file listing", description: "Load R2 context" },
      { command: "chat Build the Worker API: list objects, get presigned upload URL, delete, create folder prefix", description: "R2 API layer" },
      { command: "chat Build the frontend file manager UI: breadcrumbs, file list, drag-drop upload, preview", description: "UI generation" },
      { command: "chat Generate wrangler.jsonc with R2 bucket binding and CORS configuration", description: "R2 binding config" },
    ],
  },
  {
    id: "cf-text-to-image",
    name: "Text to Image App",
    tagline: "AI image generation with Workers AI",
    description: "Build an image generation app powered by Cloudflare Workers AI — Stable Diffusion and Flux models, prompt enhancement, batch generation, and automatic R2 storage.",
    category: "Cloudflare Workers",
    model: "@cf/black-forest-labs/flux-1-schnell",
    tags: ["workers-ai", "image-gen", "stable-diffusion", "flux", "cloudflare"],
    difficulty: "beginner",
    estimatedTime: "~2 min",
    icon: "🎨",
    useCases: ["Content creation", "Design prototyping", "Marketing assets", "Product mockups"],
    steps: [
      { command: "remember template: Text to Image — Workers AI, @cf/black-forest-labs/flux-1-schnell, R2 storage", description: "Load image gen context" },
      { command: "chat Write the Worker with AI binding: prompt input, flux-1-schnell generation, base64 output", description: "Image generation Worker" },
      { command: "chat Add prompt enhancement with Workers AI text model before image generation", description: "Prompt enhancement" },
      { command: "chat Build the simple UI with prompt textarea, generate button, and image display grid", description: "Frontend UI" },
    ],
  },
  {
    id: "cf-backend-openapi",
    name: "Backend OpenAPI Template",
    tagline: "Production-grade REST API with auto-generated docs",
    description: "Complete backend API using Hono + Chanfana (OpenAPI spec) + D1 database + Vitest testing. Auto-generates Swagger docs at /docs. Type-safe, tested, and production-ready.",
    category: "Cloudflare Workers",
    model: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    tags: ["hono", "openapi", "rest-api", "d1", "vitest", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "📋",
    useCases: ["SaaS backend", "Mobile app API", "Microservices", "Internal tools"],
    steps: [
      { command: "remember template: Hono + Chanfana + D1 + Vitest — auto-generated OpenAPI docs, type-safe CRUD", description: "Load OpenAPI template" },
      { command: "chat Scaffold the Hono app with Chanfana: defineRoute, ZodObject schema, auto-generated /openapi.json", description: "Hono + Chanfana scaffolding" },
      { command: "parallel 2 generate: D1 repository pattern with Drizzle + Vitest integration tests", description: "Data layer + tests" },
      { command: "chat Write complete CRUD routes for Users resource with validation, errors, and pagination", description: "CRUD routes" },
    ],
  },
  {
    id: "cf-vite-react",
    name: "Vite React + Hono Fullstack",
    tagline: "Modern fullstack app on Cloudflare Workers",
    description: "Fullstack template: React 19 + Vite frontend with Hono API backend, all deployed to Cloudflare Workers with Workers Assets. Single deploy command, zero cold starts.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["react", "vite", "hono", "fullstack", "workers-assets", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~4 min",
    icon: "⚛️",
    useCases: ["SaaS app", "Admin dashboard", "Internal tool", "Landing page with API"],
    steps: [
      { command: "remember template: Vite React 19 + Hono + Workers Assets — single wrangler deploy", description: "Load fullstack template" },
      { command: "chat Scaffold the Hono server with API routes and static asset serving for Vite build output", description: "Hono server setup" },
      { command: "chat Set up Vite config with base path, proxy for local dev, and TypeScript paths", description: "Vite config" },
      { command: "chat Write vite.config.ts, wrangler.jsonc, and package.json scripts for dev + deploy", description: "Build + deploy config" },
    ],
  },
  {
    id: "cf-saas-admin",
    name: "SaaS Admin Dashboard",
    tagline: "Production admin panel with Cloudflare stack",
    description: "Full admin dashboard template using Astro + shadcn/ui + Cloudflare D1 + Workers — user management, analytics, billing, and role-based access control out of the box.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["admin", "saas", "astro", "shadcn", "dashboard", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~6 min",
    icon: "🏛️",
    useCases: ["SaaS admin panel", "Internal dashboard", "Customer portal", "Analytics viewer"],
    steps: [
      { command: "remember template: Astro + shadcn/ui + D1 + Workers — SaaS admin dashboard, RBAC", description: "Load admin template" },
      { command: "parallel 3 generate: user management UI + analytics charts + billing integration stub", description: "Parallel admin section generation" },
      { command: "chat Write the role-based auth middleware and protected route patterns for Astro", description: "RBAC middleware" },
      { command: "chat Generate the D1 schema for users, roles, audit_log, and billing_events tables", description: "Admin database schema" },
    ],
  },
  {
    id: "cf-website-builder",
    name: "Website Builder Platform",
    tagline: "Let users deploy their own Workers sites",
    description: "Build a website hosting platform using Workers for Platforms — users create and deploy their own sites through a web UI, each running in isolated Worker sandboxes with custom domains.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["workers-for-platforms", "multi-tenant", "website-builder", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~6 min",
    icon: "🌐",
    useCases: ["Website builder", "No-code platform", "CMS hosting", "Multi-tenant SaaS"],
    steps: [
      { command: "remember template: Workers for Platforms — Dispatch Namespaces, custom domains, user Workers", description: "Load WfP context" },
      { command: "chat Design the platform architecture: Dispatch Namespace routing, customer Worker management API", description: "Architecture design" },
      { command: "chat Write the platform Worker with Dispatch Namespace binding to route to user Workers", description: "Platform Worker" },
      { command: "chat Build the site management API: create site, update Worker code, custom subdomain mapping", description: "Site management API" },
    ],
  },
  {
    id: "cf-multiplayer-globe",
    name: "Multiplayer Globe App",
    tagline: "Live visitor locations on a 3D globe",
    description: "Display website visitor locations in real-time on a 3D WebGL globe using Cloudflare Durable Objects and Workers — uses CF-IPCountry header for geo, zero external APIs.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["durable-objects", "websocket", "geo", "visualization", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~3 min",
    icon: "🌍",
    useCases: ["Live dashboard", "Analytics visualization", "Social proof display", "Community map"],
    steps: [
      { command: "remember template: Multiplayer Globe — Durable Objects, CF-IPCountry, WebGL globe, real-time sync", description: "Load globe template" },
      { command: "chat Write the Durable Object for tracking connected visitors with geo coordinates", description: "Visitor tracking DO" },
      { command: "chat Generate the Three.js/WebGL globe frontend with real-time dot placement from WebSocket", description: "Globe frontend" },
      { command: "chat Wire up the Worker router to extract CF-IPCountry and forward to DO via stub", description: "Geo routing" },
    ],
  },
  {
    id: "cf-worker-publisher",
    name: "Worker Publisher Template",
    tagline: "Dynamically create and deploy Workers via API",
    description: "A Cloudflare Worker that creates and deploys other Workers to a Dispatch Namespace using the Cloudflare REST API. Perfect for AI-driven code execution and multi-tenant platforms.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["dispatch-namespace", "workers-for-platforms", "dynamic", "api", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~4 min",
    icon: "📦",
    useCases: ["AI code execution", "Plugin systems", "Dynamic microservices", "Tenant isolation"],
    steps: [
      { command: "remember template: Worker Publisher — CF API, Dispatch Namespace, dynamic Worker upload", description: "Load publisher context" },
      { command: "chat Write the Worker that calls CF API to upload new Worker scripts to a Dispatch Namespace", description: "Worker publisher code" },
      { command: "chat Add validation, sandboxing limits (CPU/memory), and custom variable injection", description: "Sandboxing + limits" },
      { command: "chat Generate the complete Cloudflare API calls with auth headers and namespace routing", description: "CF API integration" },
    ],
  },
  {
    id: "cf-workers-notifications",
    name: "Workers Build Notifications",
    tagline: "Deploy notifications to Slack / Discord",
    description: "Send Workers build status notifications to Slack, Discord, or any webhook endpoint via Cloudflare Event Subscriptions — success, failure, and deployment summaries.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["webhooks", "slack", "discord", "ci-cd", "notifications", "cloudflare"],
    difficulty: "beginner",
    estimatedTime: "~2 min",
    icon: "🔔",
    useCases: ["CI/CD alerts", "Deployment monitoring", "Team notifications", "Status page updates"],
    steps: [
      { command: "remember template: Workers Builds Notifications — Event Subscriptions, Slack webhook, Discord embed", description: "Load notifications template" },
      { command: "chat Write the Worker that receives CF Event Subscription payloads and formats them for Slack/Discord", description: "Notification Worker" },
      { command: "chat Add rich formatting: deployment duration, commit info, error excerpts, and deploy URL", description: "Rich notification format" },
      { command: "chat Generate wrangler.jsonc with Event Subscriptions config and Slack/Discord webhook setup", description: "Config + webhook setup" },
    ],
  },
  {
    id: "cf-x402-payment",
    name: "x402 Payment-Gated API",
    tagline: "Pay-per-request API with on-chain micropayments",
    description: "Transparent proxy with payment-gated routes using the x402 protocol and stateless JWT authentication — charge per API call with crypto micropayments, zero traditional billing.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["payments", "x402", "crypto", "micropayments", "api", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "💳",
    useCases: ["Pay-per-use AI API", "Metered data access", "Premium content gating", "Micropayment infrastructure"],
    steps: [
      { command: "remember template: x402 — payment-gated proxy, stateless JWT, x402 protocol, micropayments", description: "Load x402 template" },
      { command: "chat Implement the x402 payment verification middleware for Cloudflare Workers", description: "Payment middleware" },
      { command: "parallel 2 generate: JWT auth flow for stateless sessions + upstream proxy with payment header injection", description: "Auth + proxy" },
      { command: "chat Write the x402 payment challenge/response flow and Coinbase Commerce integration", description: "Payment flow" },
    ],
  },
  {
    id: "cf-react-router-hono",
    name: "React Router + Hono Fullstack",
    tagline: "Full-stack with React Router 7 + Hono",
    description: "Modern full-stack template: React Router 7 (framework mode) + Hono API + shadcn/ui + Tailwind CSS, all deployed to Cloudflare Workers. File-based routing, SSR, API routes.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["react-router", "hono", "shadcn", "fullstack", "ssr", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~4 min",
    icon: "🛣️",
    useCases: ["SaaS web app", "Marketing site with API", "Dashboard", "E-commerce storefront"],
    steps: [
      { command: "remember template: React Router 7 + Hono + shadcn/ui + D1 + Workers — SSR fullstack", description: "Load RR+Hono template" },
      { command: "chat Scaffold React Router 7 in framework mode with file-based routing and SSR config for Workers", description: "React Router setup" },
      { command: "chat Create the Hono API layer with D1 binding, Zod validation, and shared type contracts", description: "Hono API + D1" },
      { command: "chat Set up shadcn/ui components, Tailwind CSS, and the wrangler.jsonc with asset binding", description: "UI + deploy config" },
    ],
  },
  {
    id: "cf-remix-starter",
    name: "Remix Framework Starter",
    tagline: "Full-stack Remix on Cloudflare Workers",
    description: "Build a full-stack Remix application deployed to Cloudflare Workers Assets — server-side rendering, data loaders, action forms, and D1 database. Zero infrastructure to manage.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["remix", "ssr", "fullstack", "workers-assets", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~4 min",
    icon: "💿",
    useCases: ["Content site", "CRUD app", "Multi-page SaaS", "Blog platform"],
    steps: [
      { command: "remember template: Remix + Workers Assets + D1 — SSR loaders, actions, progressive enhancement", description: "Load Remix template" },
      { command: "chat Create Remix app with Workers adapter: loader/action patterns for D1 data access", description: "Remix loaders + actions" },
      { command: "chat Set up server-side sessions with D1, form validation with Zod, and error boundaries", description: "Session + validation" },
      { command: "chat Generate wrangler.jsonc with D1 binding, Workers Assets config, and CI deploy script", description: "Deploy configuration" },
    ],
  },
  {
    id: "cf-nextjs-starter",
    name: "Next.js on Cloudflare",
    tagline: "Next.js 15 with Workers + D1 + R2",
    description: "Deploy a full-stack Next.js 15 application to Cloudflare Workers using @opennextjs/cloudflare adapter — App Router, RSC, D1 for database, R2 for files, edge runtime.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["nextjs", "react", "ssr", "app-router", "cloudflare"],
    difficulty: "intermediate",
    estimatedTime: "~4 min",
    icon: "▲",
    useCases: ["Marketing site", "SaaS app", "Blog", "E-commerce"],
    steps: [
      { command: "remember template: Next.js 15 + @opennextjs/cloudflare + D1 + R2 — App Router, RSC, edge", description: "Load Next.js CF template" },
      { command: "chat Configure next.config.ts for @opennextjs/cloudflare adapter with D1 and R2 bindings", description: "Next.js CF config" },
      { command: "chat Create a Server Component that reads from D1 via getCloudflareContext() binding", description: "D1 data access in RSC" },
      { command: "chat Generate wrangler.jsonc, deploy command, and environment variable mapping", description: "Deploy + env setup" },
    ],
  },
  {
    id: "cf-astro-starter",
    name: "Astro on Cloudflare",
    tagline: "Astro with Workers + content collections",
    description: "Build and deploy an Astro site to Cloudflare Workers — content collections, image optimization, View Transitions, D1 for dynamic data, and SSR islands for interactivity.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["astro", "ssg", "ssr", "content", "cloudflare"],
    difficulty: "beginner",
    estimatedTime: "~2 min",
    icon: "🚀",
    useCases: ["Blog", "Documentation site", "Marketing landing page", "Portfolio"],
    steps: [
      { command: "remember template: Astro + Cloudflare adapter — content collections, View Transitions, D1, image opt", description: "Load Astro CF template" },
      { command: "chat Scaffold Astro site with Cloudflare adapter: astro.config.mjs, content collections schema", description: "Astro scaffolding" },
      { command: "chat Create layout with View Transitions, blog collection, and interactive React island", description: "Astro components" },
      { command: "chat Generate wrangler deploy config and Astro build command integration", description: "Astro deploy" },
    ],
  },
  {
    id: "cf-todo-app",
    name: "To-Do List App",
    tagline: "Full-stack to-do with D1 and Workers Assets",
    description: "A complete to-do list application built with Cloudflare Workers Assets and Remix — real-time sync, user auth, shared lists, and offline support. Zero infrastructure needed.",
    category: "Cloudflare Workers",
    model: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tags: ["todo", "remix", "d1", "workers-assets", "beginner", "cloudflare"],
    difficulty: "beginner",
    estimatedTime: "~2 min",
    icon: "✅",
    useCases: ["Task management", "Project tracking", "Shopping lists", "Learning app patterns"],
    steps: [
      { command: "remember template: To-Do App — Remix + D1 + Workers Assets, optimistic UI, shared lists", description: "Load to-do template" },
      { command: "chat Write the Remix routes with D1 loader + action for CRUD to-do operations", description: "CRUD implementation" },
      { command: "chat Add optimistic UI updates and offline-capable fetch patterns", description: "Offline + optimistic" },
      { command: "chat Generate D1 migration SQL and complete wrangler.jsonc config", description: "DB + deploy config" },
    ],
  },
  {
    id: "cf-react-postgres",
    name: "React + Postgres Fullstack",
    tagline: "Traditional SQL with Cloudflare Workers",
    description: "Full-stack app using React (Vite) + Hono backend + Hyperdrive for Postgres connection pooling on Cloudflare Workers. Real Postgres at the edge, no connection limit issues.",
    category: "Cloudflare Workers",
    model: "gpt-5.2",
    tags: ["postgres", "hyperdrive", "react", "hono", "fullstack", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "🐘",
    useCases: ["Migrate existing Postgres app to edge", "High-traffic API", "Analytics backend", "SaaS data layer"],
    steps: [
      { command: "remember template: React + Postgres + Hyperdrive — connection pooling, Drizzle ORM, Hono backend", description: "Load Postgres CF template" },
      { command: "chat Set up Hyperdrive binding with Drizzle ORM for type-safe Postgres queries in Workers", description: "Hyperdrive + Drizzle" },
      { command: "chat Write the Hono API with Postgres queries, connection reuse, and proper error handling", description: "API with Postgres" },
      { command: "chat Configure wrangler.jsonc with Hyperdrive binding and environment variable for DATABASE_URL", description: "Hyperdrive config" },
    ],
  },

  // ── Dynamic Workers ─────────────────────────────────────────────────────────
  {
    id: "dynamic-worker-sandbox",
    name: "Dynamic Worker Sandbox",
    tagline: "AI-generated code in isolated V8 sandbox",
    description: "Use Cloudflare's Dynamic Worker Loader (open beta) to execute AI-generated code in isolated V8 sandboxes — < 5ms cold start, no containers needed. The foundation for safe AI code execution at scale.",
    category: "Dynamic Workers",
    model: "gpt-5.2",
    tags: ["dynamic-workers", "sandbox", "v8", "ai-execution", "cloudflare", "beta"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "⚡",
    useCases: ["AI code execution", "Plugin sandboxing", "User code isolation", "AI agent tool execution"],
    steps: [
      { command: "remember context: Cloudflare Dynamic Worker Loader API — instantiate sandboxed Workers at runtime from AI-generated code, < 5ms cold start, V8 isolates not containers", description: "Load Dynamic Workers context" },
      { command: "chat Write a Cloudflare Worker using the Dynamic Worker Loader API: receive code string, instantiate sandbox Worker, call exported function, return result", description: "Dynamic Worker Loader implementation" },
      { command: "parallel 2 analyze: security boundaries and capability injection patterns + error handling for sandbox failures", description: "Security + error analysis" },
      { command: "chat Design the full AI agent sandbox system: LLM generates code → Dynamic Worker executes it → results stream back to user", description: "Full AI sandbox architecture" },
    ],
  },
  {
    id: "dynamic-worker-agent",
    name: "AI Code Execution Agent",
    tagline: "Agents that write and execute their own code",
    description: "Build an AI agent that writes code to solve tasks, then executes it in isolated Dynamic Workers — Code Mode pattern from Cloudflare. 81% fewer tokens than tool calls, completely sandboxed.",
    category: "Dynamic Workers",
    model: "gpt-5.2",
    tags: ["dynamic-workers", "code-mode", "ai-agent", "sandboxing", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~6 min",
    icon: "🤖",
    useCases: ["AI coding assistant", "Autonomous agent backend", "Code-based MCP server", "Self-improving agent"],
    steps: [
      { command: "remember context: Code Mode — agent writes code calling APIs (81% fewer tokens than tool calls), Dynamic Worker executes in V8 sandbox, Cloudflare MCP server pattern", description: "Load Code Mode context" },
      { command: "chat Design the agent loop: user request → LLM generates TypeScript → Dynamic Worker executes → result returned → loop continues if needed", description: "Code Mode agent architecture" },
      { command: "chat Write the Dynamic Worker Loader sandbox: inject env bindings, execute generated code, capture output and errors", description: "Sandbox implementation" },
      { command: "parallel 2 generate: LLM prompt engineering for code generation + retry/correction loop when code fails", description: "LLM prompting + retry loop" },
    ],
  },
  {
    id: "dynamic-worker-mcp",
    name: "Dynamic MCP Server",
    tagline: "Build an MCP server with Dynamic Workers",
    description: "Create a Cloudflare MCP server that uses Dynamic Worker Loader to execute any API behind just two tools — inspired by the Cloudflare MCP server pattern. Under 1,000 tokens to describe everything.",
    category: "Dynamic Workers",
    model: "gpt-5.2",
    tags: ["mcp", "dynamic-workers", "code-mode", "tools", "cloudflare"],
    difficulty: "advanced",
    estimatedTime: "~5 min",
    icon: "🔧",
    useCases: ["Universal API proxy", "AI tool server", "LLM function calling", "Code-based tools"],
    steps: [
      { command: "remember context: Cloudflare MCP server — two tools only: list_apis and execute_code, Dynamic Worker executes the generated code, < 1000 token description", description: "Load MCP Dynamic Worker context" },
      { command: "chat Write a Cloudflare Workers MCP server with two tools: list_apis(category) and execute_code(code_string)", description: "MCP server implementation" },
      { command: "chat Implement the Dynamic Worker Loader call inside execute_code: sandbox isolation, timeout, env bindings for KV/D1/R2/AI", description: "Dynamic execution in execute_code" },
      { command: "chat Generate the API registry that list_apis returns — structured TypeScript interfaces for available Cloudflare services", description: "API registry" },
    ],
  },
  {
    id: "dynamic-worker-swarm",
    name: "Distributed AI Agent Swarm",
    tagline: "Run N agents in parallel Dynamic Workers",
    description: "Spawn an entire swarm of AI agents — each in its own isolated Dynamic Worker V8 sandbox — that work in parallel on sub-tasks, communicate via Durable Objects, and aggregate results.",
    category: "Dynamic Workers",
    model: "gpt-5.2",
    tags: ["dynamic-workers", "swarm", "parallel", "durable-objects", "ai-agent"],
    difficulty: "advanced",
    estimatedTime: "~8 min",
    icon: "🐝",
    useCases: ["Parallel AI processing", "Distributed computation", "Multi-agent research", "Horizontal AI scaling"],
    steps: [
      { command: "remember context: Multi-agent swarm via Dynamic Workers — orchestrator Worker spawns N agent Workers via Dynamic Worker Loader, agents communicate via DO message bus, results aggregated", description: "Load swarm architecture context" },
      { command: "chat Design the swarm orchestrator: receive goal → decompose into N tasks → spawn N Dynamic Workers in parallel → wait for all → synthesize", description: "Swarm orchestrator design" },
      { command: "chat Write the agent Worker template: receives task + context → executes → returns structured result to orchestrator", description: "Agent Worker template" },
      { command: "parallel 2 generate: Durable Object message bus for agent coordination + result aggregation and synthesis layer", description: "DO coordination + synthesis" },
    ],
  },
];

export function getWorkflowById(id: string): AgenticWorkflow | undefined {
  return AGENTIC_WORKFLOWS.find((w) => w.id === id);
}

export function getWorkflowsByCategory(category: WorkflowCategory): AgenticWorkflow[] {
  return AGENTIC_WORKFLOWS.filter((w) => w.category === category);
}

export const DIFFICULTY_COLORS = {
  beginner: "text-green-400 border-green-400/30 bg-green-400/10",
  intermediate: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
  advanced: "text-red-400 border-red-400/30 bg-red-400/10",
} as const;

export const CATEGORY_ICONS: Record<WorkflowCategory, string> = {
  "Code Intelligence": "💻",
  "Research & Analysis": "🔬",
  "Data Processing": "📊",
  "Content Generation": "✍️",
  "Parallel Agents": "⚡",
  "DevOps & Deploy": "🚀",
  "AI & Models": "🤖",
  "Business & Strategy": "📈",
  "Cloudflare Workers": "☁️",
  "Dynamic Workers": "⚡️",
};
